project:
  type: website

website:
  title: "Data tidying and importing"
  navbar:
    tools:
        - icon: github
          href: https://github.com/data-science-with-r
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    highlight-style: a11y-dark

execute:
  freeze: auto

editor: visual