---
title: "That's my type (Complete)"
---

In the following exercises, first guess what type the vector will be coerced to, then check your intuition with the `typeof()` function.

1.  `c(1, 1L, "C")`

```{r}
#| label: view-1
c(1, 1L, "C")
```

```{r}
#| label: help-1
1
1L
"C"
```

Guess: \_\_\_

```{r}
#| label: check-1
typeof(c(1, 1L, "C"))
```

2.  `c(1L / 0, "A")`

```{r}
#| label: view-2
c(1L / 0, "A")
```

```{r}
#| label: help-2
typeof(1L)
typeof(0)
typeof(1L/0)
typeof("A")
```

Guess: \_\_\_

```{r}
#| label: check-2
typeof(c(1L / 0, "A"))
```

3.  `c(1:3, 5)`

```{r}
#| label: view-3
c(1:3, 5)
```

```{r}
#| label: help-3
typeof(1:3)
typeof(5)
```

Guess: \_\_\_

```{r}
#| label: check-3
typeof(c(1:3, 5))
```

4.  `c(3, "3+")`

```{r}
#| label: view-4
c(3, "3+")
```

```{r}
#| label: help-4
typeof(3)
typeof("3+")
```

Guess: \_\_\_

```{r}
#| label: check-4
typeof(c(3, "3+"))
```

5.  `c(NA, TRUE)`

```{r}
#| label: view-5
c(NA, TRUE)
```

```{r}
#| label: help-5
typeof(NA)
typeof(TRUE)
```

Guess: \_\_\_

```{r}
#| label: check-5
typeof(c(NA, TRUE))
```
